### ISSUE TITLE
Implement Solidity v0.8.4 custom errors

### ISSUE THREAD

**Issue by paulrberg** [hifi-finance/prb-math#30]
See this [tweet](https://twitter.com/PaulRBerg/status/1387471133528760328).

**Comment by paulrberg** [comment]
Waiting after Waffle and Solhint:

+ https://github.com/EthWorks/Waffle/issues/511
+ https://github.com/protofire/solhint/issues/289

**Comment by axic** [comment]
This seems to be implemented by now?

**Comment by paulrberg** [comment]
Yes! Thanks for the heads-up, @axic.

Support for custom errors was added in https://github.com/hifi-finance/prb-math/commit/04b25fd7fd1351ec54dbb0de24f53cde34c564c4.
